<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'The file "{file}" is not an image.' => 'Файл "{file}" не є зображенням.',
  'The image "{file}" height should be "{height}px".' => 'Зображення "{file}" повинно бути {height} пикселів у висоту.',
  'The image "{file}" height should be at least "{height}px".' => 'Зображення "{file}" повинно бути не менше {height} пикселів у висоту.',
  'The image "{file}" height should be at most "{height}px".' => 'Зображення "{file}" повинно бути не більше {height} пикселів у висоту.',
  'The image "{file}" mime type "{mime}" is not allowed.' => 'Зображення "{file}" має недопустимий тип "{mime}"',
  'The image "{file}" width should be "{width}px".' => 'Зображення "{file}" повинно бути {width} пикселів у ширину.',
  'The image "{file}" width should be at least "{width}px".' => 'Зображення "{file}" повинно бути не менше {width} пикселів у ширину.',
  'The image "{file}" width should be at most "{width}px".' => 'Зображення "{file}" повинно бути не більше {width} пикселів у ширину.',
  'The image "{file}" small side should be "{side}px".' => 'Менша сторона зображення "{file}" повинна бути {width} пикселів.',
  'The image "{file}" small side should be at least "{side}px".' => 'Менша сторона зображення "{file}" повинна бути не менше {width} пикселів.',
  'The image "{file}" small side should be at most "{side}px".' => 'Менша сторона зображення "{file}" повинна бути не більше {width} пикселів.',
  'The image "{file}" big side should be "{side}px".' => 'Більша сторона зображення "{file}" повинна бути {width} пикселів.',
  'The image "{file}" big side should be at least "{side}px".' => 'Більша сторона зображення "{file}" повинна бути не менше {width} пикселів.',
  'The image "{file}" big side should be at most "{side}px".' => 'Більша сторона зображення "{file}" повинна бути не більше {width} пикселів.',
);
