<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'Banner' => 'Bannière',
  'Click to access {url}...' => 'Cliquez pour accéder à {url}...',
  'Description' => 'Description',
  'Description (Hover text)' => 'Description (Texte de survol)',
  'Filesize of the banner\'s image in kB' => 'Taille de l\'image de la bannière en ko',
  'Height of the banner\'s image in pixels' => 'Hauteur de l\'image de la bannière en pixels',
  'Link Title' => 'Texte du lien',
  'Link URL' => 'URL du lien',
  'More information...' => 'Plus d\'informations...',
  'Text Line' => 'Ligne de texte',
  'The image should be in jpeg (jpg), png or gif format with a dimension of :width*:heightpx and have a maximum filesize of :filesizekB' => '',
  'There is nothing to configure for this ad type.' => 'Il n\'y a rien à configurer pour ce type de publicité',
  'Title' => 'Titre',
  'Width of the banner\'s image in pixels' => 'Largeur de l\'image de la bannière en pixels',
  'Your ad here' => 'Votre publicité ici',
);
