<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  ' is not a valid HTTP header name' => '',
  '$config expects an array, NULL received.' => '',
  '\'\' is not a valid HTTP request method.' => '',
  'Array or Zend_Config object expected, given {parameter}' => '',
  'Cannot handle "" transfer encoding' => '',
  'Cannot set a file-handle for cURL option CURLOPT_INFILE without also setting its size in CURLOPT_INFILESIZE.' => '',
  'Cookie name cannot contain these characters: =,; 	
 ()' => '',
  'Error in cURL request: {error}' => '',
  'Error writing request to proxy server' => '',
  'Error writing request to server' => '',
  'Expected array parameter, given {parameter}' => '',
  'Invalid chunk size "" unable to read chunked body' => '',
  'Invalid parameter type passed as CookieJar' => '',
  'Method currently not supported' => '',
  'No valid URI has been passed to the client' => '',
  'Not a supported HTTP authentication type: \'{type}\'' => '',
  'Passed adapter is not a HTTP connection adapter' => '',
  'Passed parameter is not a valid HTTP URI.' => '',
  'Streaming requests are allowed only with PUT' => '',
  'The user name cannot contain \':\' in \'Basic\' HTTP authentication' => '',
  'Trying to write but we are connected to the wrong host' => '',
  'Trying to write but we are connected to the wrong proxy server' => '',
  'Trying to write but we are not connected' => '',
  'Unable to Connect to {host}:{port}' => '',
  'Unable to Connect to {host}:{port} {errno}:{errstr}' => '',
  'Unable to connect to HTTPS proxy. Server response: {response}' => '',
  'Unable to connect to HTTPS server through proxy: could not negotiate secure connection.' => '',
  'Unable to load adapter {adapter}: {message}' => '',
  'Unable to read file \'\' for upload' => '',
  'Unable to read response, or response is empty' => '',
  'Unable to set sslcert option' => '',
  'Unable to set sslpassphrase option' => '',
  'Unable to set the connection timeout' => '',
  'Unknown or erroreous cURL option \'{k}\' set' => '',
  'cURL extension has to be loaded to use this Zend_Http_Client adapter.' => '',
  'Cookie name cannot contain these characters: =,; 	
 ()' => '@@@@@@@@@@@@@@@@@@@@@@@@@@@@',
);
