<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'The file "{file}" is not an image.' => 'Le fichier "{file}" n\'est pas une image.',
  'The image "{file}" big side should be "{side}px".' => 'L\'image "{file}" devrait avoir un grand côté de "{side}px".',
  'The image "{file}" big side should be at least "{side}px".' => 'L\'image "{file}" devrait avoir un grand côté d\'au moins "{side}px".',
  'The image "{file}" big side should be at most "{side}px".' => 'L\'image "{file}" devrait avoir un grand côté d\'au plus "{side}px".',
  'The image "{file}" height should be "{height}px".' => 'L\'image "{file}" devrait avoir une hauteur de "{height}px".',
  'The image "{file}" height should be at least "{height}px".' => 'L\'image "{file}" devrait avoir une hauteur d\'au moins "{height}px".',
  'The image "{file}" height should be at most "{height}px".' => 'L\'image "{file}" devrait avoir une hauteur d\'au plus "{height}px".',
  'The image "{file}" mime type "{mime}" is not allowed.' => 'L\'image "{file}" a un type mime "{mime}" non autorisé.',
  'The image "{file}" small side should be "{side}px".' => 'L\'image "{file}" devrait avoir un petit côté de "{side}px".',
  'The image "{file}" small side should be at least "{side}px".' => 'L\'image "{file}" devrait avoir un petit côté d\'au moins "{side}px".',
  'The image "{file}" small side should be at most "{side}px".' => 'L\'image "{file}" devrait avoir un petit côté d\'au plus "{side}px".',
  'The image "{file}" width should be "{width}px".' => 'L\'image "{file}" devrait avoir une largeur de "{width}px".',
  'The image "{file}" width should be at least "{width}px".' => 'L\'image "{file}" devrait avoir une largeur d\'au moins "{width}px".',
  'The image "{file}" width should be at most "{width}px".' => 'L\'image "{file}" devrait avoir une largeur d\'au plus "{width}px".',
);
