<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'Account funding' => 'Approvisionnement du compte',
  'Add this amount' => 'Ajouter ce montant',
  'Allopass allows you to add funds via micropayment, using SMS, phone call, credit card or other means of payment' => 'Allopass vous permet d\'ajouter des fonds via micropaiement par SMS, appel téléphonique, carte de crédit ou autres moyens de paiement',
  'Check the amount remaining above to see how much you still need to add.' => 'Vérifiez le montant restant ci-dessus pour voir combien vous devez encore ajouter.',
  'Click the button below to proceed with the PayPal payment.' => 'Cliquez sur le bouton ci-dessous pour procéder au paiement PayPal.',
  'If you don\'t have any vouchers left to use, please use the link below to finish the process.' => 'Si vous n\'avez plus de bons d\'achat restants à utiliser, veuillez cliquer sur le lien ci-dessous pour terminer le processus.',
  'If you just did a PayPal payment and it hasn\'t been taken into account yet, please refresh the page.' => 'Si vous venez de faire un paiement PayPal et il n\'a pas encore été prise en compte, veuillez s\'il vous plaît rafraîchir la page.',
  'PayPal allows you to add funds from a Paypal account or using your credit card' => 'PayPal vous permet d\'ajouter des fonds à partir d\'un compte Paypal ou par carte de crédit',
  'Please enter your voucher\'s code below.' => 'Veuillez entrer le code de votre bon d\'achat ci-dessous.',
  'Since Allopass works with codes of different value, every payment will fund your account with the exact amount we receive from it. You may have to do more than one payment to add a large amount of money to your account.' => 'Puisqu\'Allopass fonctionne avec des codes de valeurs différentes, chaque paiement approvisionnera votre compte du montant exact que nous recevons de lui. Vous pourriez avoir à faire plus d\'un paiement si vous souhaitez ajouter une grande quantité d\'argent sur votre compte.',
  'The total value of your voucher will then be added to your account.' => 'La valeur totale de votre bon d\'achat sera ensuite ajoutée à votre compte.',
  'The transaction couldn\'t be processed : :error' => 'La transaction n\'a pu être traitée : :error',
  'The transaction wan\'t reported as successful' => 'La transaction n\'a pas été signalée comme réussie',
  'The voucher code you entered is invalid.' => 'Le code du bon d\'achat que vous avez entré est invalide.',
  'The voucher code you entered is reserved to another account.' => 'Le code du bon d\'achat que vous avez entré est réservé à un autre compte.',
  'The voucher code you entered was already used.' => 'Le code du bon d\'achat que vous avez entré a déjà été utilisé.',
  'The voucher\'s amount of :amount € was added to your account.' => 'Le montant du bon d\'achat de :amount € a été ajouté à votre compte.',
  'Use a voucher that was given to you' => 'Utilisez un bon d\'achat qui vous a été fourni',
  'Voucher' => 'Bon d\'achat',
  'Voucher code' => 'Code du bon d\'achat',
);
